### ISSUE TITLE
One question about your work...

### ISSUE THREAD

**Issue by ruobing-wang** [ustc-compiler-macrofication/macrofication#1]
macrofication是如何在sweet.js中具体实现的？重构过程是在程序执行的哪个阶段运行？希望详细阐述下。

**Comment by yuhao318** [comment]
在重构过程在从parser生成ast树时macrofication就已经被read和expand；

**Comment by yuhao318** [comment]
sweetjs实现macrofication是一个比较复杂的过程，大致说来lexer先把源码token化, 得到token序列，之后再变成token树, 变term树，根据定义的macro匹配扩展token树, 再parse成AST，在实现中尤其要注意一些macrofication的特性，sweet.js提供了模式变量匹配特定模式类以及匹配单个或重复标记的功能。模式类还允许宏匹配多个tokens。
