### ISSUE TITLE
[组间互动] 为什么JavaScript需要Macrofication，而不是一般的宏机制？

### ISSUE THREAD

**Issue by Robert-Lu** [ustc-compiler-macrofication/macrofication#2]
我有一个不知是否正确的先验认知：JavaScript是一门在创造之初并没有经过深思熟虑的语言，它有许多缺陷以及历史遗留问题。甚至给多年来的web开发者带来了很多不必要的痛苦。请问经过一系列调研之后，您是否认同这样的认知呢？

请问 Macrofication 是否是与 JavaScript 的语言特性密切关联的技术？如果是的话，为什么 JavaScript 需要Macrofication，而不是一般的宏机制？

**Comment by yuhao318** [comment]
没错，JavaScript最开始创建的时候缺陷确实很多，这也为其后来的扩展带来了很多问题，在论文中提到的Macrofication实现在https://github.com/sweet-js 给出了源码，其他语言通常使用的Macrofication就是为了解决其宏扩展的问题而创建的。
JavaScript不适用一般的string-based宏，在这里，我们考虑的宏的类型是一个更受限制的形式，称为"pattern-template macros"，他是基于parser-level层次，在js中已经有了marco的实现，Macrofication是给出了自制js的macro的机制，这会使得代码更加灵活。
